name: Node App Pipeline
run-name: ${{ github.actor }} running node app
on: [push]
jobs:
  #job
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          node-version: '14'
      - run: npm install
      - run: npm test

     
  